### ISSUE TITLE
GET /blockchain/sessions returns an empty error

### ISSUE THREAD

**Issue by tshak** [Lumerin-protocol/Morpheus-Lumerin-Node#190]
## Repro
```
curl http://localhost:8082/blockchain/sessions
```

## Expected

A JSON response with an error indicating that `user or provider is required`. 

A log message in server logs with a similar error

## Actual

An empty JSON response: `{"error":{}}`

A log message containing Error <Nil>

Note: it looks like `err` is always `nil` here
https://github.com/Lumerin-protocol/Morpheus-Lumerin-Node/blob/dev/proxy-router/internal/blockchainapi/controller.go#L669

**Comment by abs2023** [comment]
@alex-sandrk can you please take a look?  Reproduceable directly via swagger (no prompting of what is missing from the request).  
![image](https://github.com/user-attachments/assets/094d04f8-1d3e-4b9a-8cff-a6ba3f46bc1f)

**Comment by alex-sandrk** [comment]
Thank you for your MR, it's merged. Also, I agree with Alan about splitting this command into two separate. Here is PR:
https://github.com/Lumerin-protocol/Morpheus-Lumerin-Node/pull/195
