### ISSUE TITLE
The method `GetFiles` uses a `*gin.Context` as its context parameter, which is inconsistent with other methods in the same file that use the standard `context.Context`. This inconsistency can lead to confusion and potential bugs, especially in a larger codebase where context passing and manipulation are common. It's recommended to standardize the context usage across all methods to ensure consistency and avoid potential issues with context handling.

### ISSUE THREAD

**Issue by srt0422** [Lumerin-protocol/Morpheus-Lumerin-Node#25]
The method `GetFiles` uses a `*gin.Context` as its context parameter, which is inconsistent with other methods in the same file that use the standard `context.Context`. This inconsistency can lead to confusion and potential bugs, especially in a larger codebase where context passing and manipulation are common. It's recommended to standardize the context usage across all methods to ensure consistency and avoid potential issues with context handling.

_Originally posted by @codereviewbot-ai[bot] in https://github.com/Lumerin-protocol/Morpheus-Lumerin-Node/pull/20#discussion_r1551556331_

**Comment by alex-sandrk** [comment]
gin.Context is designed to be passed as reference
