### ISSUE TITLE
Trying to access our models results in a failure to get the adapter

### ISSUE THREAD

**Issue by mrakgr** [Lumerin-protocol/Morpheus-Lumerin-Node#342]
```
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/proxyctl.(*Proxy).run.NewTCPHandler.func5
        /home/zeta/Morpheus-Lumerin-Node/proxy-router/internal/handlers/tcphandlers/tcp.go:44
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/repositories/transport.(*TCPServer).startAccepting.func1
        /home/zeta/Morpheus-Lumerin-Node/proxy-router/internal/repositories/transport/tcp_server.go:100
2024-12-06T17:57:41.421231941   WARN    MODEL_LOADER    model config not found for ID: 0x0bf03bc2111eec3b83edde36940e1475a093705d323d1121613e0ab836abc2dd
2024-12-06T17:57:46.151916022   DEBUG   received open session event, sessionId 0x92199d13a04ddfaeaa05edb3aa30df5c17bce5ac1a42d2089f65a25b6c1061f9
2024-12-06T17:57:49.708225156   WARN    MODEL_LOADER    model config not found for ID: 0x0bf03bc2111eec3b83edde36940e1475a093705d323d1121613e0ab836abc2dd
2024-12-06T17:57:49.708301441   ERROR   SRC     failed to get adapter: api adapter not found:   {"SrcAddr": "174.229.86.109:62154"}
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/proxyapi.(*ProxyReceiver).SessionPrompt
        /home/zeta/Morpheus-Lumerin-Node/proxy-router/internal/proxyapi/proxy_receiver.go:72
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/proxyapi.(*MORRPCController).sessionPrompt
        /home/zeta/Morpheus-Lumerin-Node/proxy-router/internal/proxyapi/controller_morrpc.go:157
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/proxyapi.(*MORRPCController).Handle
        /home/zeta/Morpheus-Lumerin-Node/proxy-router/internal/proxyapi/controller_morrpc.go:52
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/proxyctl.(*Proxy).run.NewTCPHandler.func5
        /home/zeta/Morpheus-Lumerin-Node/proxy-router/internal/handlers/tcphandlers/tcp.go:35
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/repositories/transport.(*TCPServer).startAccepting.func1
        /home/zeta/Morpheus-Lumerin-Node/proxy-router/internal/repositories/transport/tcp_server.go:100
2024-12-06T17:57:49.708403845   ERROR   SRC     failed to get adapter: api adapter not found:   {"SrcAddr": "174.229.86.109:62154"}
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/proxyapi.(*MORRPCController).sessionPrompt
        /home/zeta/Morpheus-Lumerin-Node/proxy-router/internal/proxyapi/controller_morrpc.go:159
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/proxyapi.(*MORRPCController).Handle
        /home/zeta/Morpheus-Lumerin-Node/proxy-router/internal/proxyapi/controller_morrpc.go:52
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/proxyctl.(*Proxy).run.NewTCPHandler.func5
        /home/zeta/Morpheus-Lumerin-Node/proxy-router/internal/handlers/tcphandlers/tcp.go:35
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/repositories/transport.(*TCPServer).startAccepting.func1
        /home/zeta/Morpheus-Lumerin-Node/proxy-router/internal/repositories/transport/tcp_server.go:100
2024-12-06T17:57:49.708462754   ERROR   SRC     Error handling message: failed to get adapter: api adapter not found:
Message: &{1 session.prompt {"signature":"0xab0ec9fd6ceab85f243b6bc9b42cf2fbb029e0ee342a8dc0f9af59b19d3375a72f1ebbf6f4a3b817799683201120d6ee8de54f8a3b9c88122ed61a763d304e2c01","sessionid":"0x92199d13a04ddfaeaa05edb3aa30df5c17bce5ac1a42d2089f65a25b6c1061f9","message":"{\"model\":\"\",\"messages\":[{\"role\":\"user\",\"content\":\"testing\"}],\"stream\":true}","timestamp":1733507869422}}
        {"SrcAddr": "174.229.86.109:62154"}
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/proxyctl.(*Proxy).run.NewTCPHandler.func5
        /home/zeta/Morpheus-Lumerin-Node/proxy-router/internal/handlers/tcphandlers/tcp.go:44
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/repositories/transport.(*TCPServer).startAccepting.func1
        /home/zeta/Morpheus-Lumerin-Node/proxy-router/internal/repositories/transport/tcp_server.go:100
2024-12-06T17:57:56.430185499   DEBUG   received close session event, sessionId 0x92199d13a04ddfaeaa05edb3aa30df5c17bce5ac1a42d2089f65a25b6c1061f9
2024-12-06T17:58:10.050686409   WARN    MODEL_LOADER    model config not found for ID: 0x0bf03bc2111eec3b83edde36940e1475a093705d323d1121613e0ab836abc2dd
2024-12-06T17:58:10.050752609   ERROR   SRC     failed to get adapter: api adapter not found:   {"SrcAddr": "174.229.86.109:62156"}
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/proxyapi.(*ProxyReceiver).SessionPrompt
        /home/zeta/Morpheus-Lumerin-Node/proxy-router/internal/proxyapi/proxy_receiver.go:72
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/proxyapi.(*MORRPCController).sessionPrompt
        /home/zeta/Morpheus-Lumerin-Node/proxy-router/internal/proxyapi/controller_morrpc.go:157
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/proxyapi.(*MORRPCController).Handle
        /home/zeta/Morpheus-Lumerin-Node/proxy-router/internal/proxyapi/controller_morrpc.go:52
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/proxyctl.(*Proxy).run.NewTCPHandler.func5
        /home/zeta/Morpheus-Lumerin-Node/proxy-router/internal/handlers/tcphandlers/tcp.go:35
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/repositories/transport.(*TCPServer).startAccepting.func1
        /home/zeta/Morpheus-Lumerin-Node/proxy-router/internal/repositories/transport/tcp_server.go:100
2024-12-06T17:58:10.050834422   ERROR   SRC     failed to get adapter: api adapter not found:   {"SrcAddr": "174.229.86.109:62156"}
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/proxyapi.(*MORRPCController).sessionPrompt
        /home/zeta/Morpheus-Lumerin-Node/proxy-router/internal/proxyapi/controller_morrpc.go:159
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/proxyapi.(*MORRPCController).Handle
        /home/zeta/Morpheus-Lumerin-Node/proxy-router/internal/proxyapi/controller_morrpc.go:52
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/proxyctl.(*Proxy).run.NewTCPHandler.func5
        /home/zeta/Morpheus-Lumerin-Node/proxy-router/internal/handlers/tcphandlers/tcp.go:35
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/repositories/transport.(*TCPServer).startAccepting.func1
        /home/zeta/Morpheus-Lumerin-Node/proxy-router/internal/repositories/transport/tcp_server.go:100
2024-12-06T17:58:10.050896085   ERROR   SRC     Error handling message: failed to get adapter: api adapter not found:
Message: &{1 session.prompt {"signature":"0x56780056bb3e6dde0bec79de4d17260d9000962e1e68b8be5df8c79cde805d2a639979391e4b6a4940797d5604b4ccaace7bc41f5469ccc50e1b6c45addc5fd900","sessionid":"0x92199d13a04ddfaeaa05edb3aa30df5c17bce5ac1a42d2089f65a25b6c1061f9","message":"{\"model\":\"\",\"messages\":[{\"role\":\"user\",\"content\":\"test\"}],\"stream\":true}","timestamp":1733507889463}}
        {"SrcAddr": "174.229.86.109:62156"}
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/proxyctl.(*Proxy).run.NewTCPHandler.func5
        /home/zeta/Morpheus-Lumerin-Node/proxy-router/internal/handlers/tcphandlers/tcp.go:44
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/repositories/transport.(*TCPServer).startAccepting.func1
        /home/zeta/Morpheus-Lumerin-Node/proxy-router/internal/repositories/transport/tcp_server.go:100
```

We got these errors while Kyle was trying out our models earlier. I need to dive deeper into this issue, so I'll back this error message here for when I get back next week.

**Comment by abs2023** [comment]
check and update your models-config.json against the new format/schema.... this is showing that it's not able to load the models
`2024-12-06T17:57:41.421231941   WARN    MODEL_LOADER    model config not found for ID: 0x0bf03bc2111eec3b83edde36940e1475a093705d323d1121613e0ab836abc2dd`

Please see https://github.com/Lumerin-protocol/Morpheus-Lumerin-Node/blob/main/docs/models-config.json.md for the updated format.

**Comment by mrakgr** [comment]
I am not inputting the models by hand onto the `models_config.json` file, but instead codegen it based on the data in the F# scripts I am using, so it was quite easy for me to adapt it to the new schema. Now that I've done this, I see that I am not getting warnings about it failing to load. Take a look at what sort of error I got yesterday:

```
2024-12-06T18:00:22.621162643   WARN    MODEL_LOADER    failed to unmarshal to new models config, trying legacy
2024-12-06T18:00:22.621251397   WARN    failed to load model config, running with empty: invalid models config: validator: (nil config.ModelConfigs)
```

This is a warning, but it should have been an error.

**Comment by mrakgr** [comment]
I put up the bids, so let me try it out.

**Comment by mrakgr** [comment]
![image](https://github.com/user-attachments/assets/27726459-48e4-4a17-92ca-ebf267cb22b0)
Ok, the first issue I am running into is with the proxy router on the consumer side. I got the 1.2 release for the mainnet, but it's telling me it's configured for the testnet here.

**Comment by mrakgr** [comment]
One other issue that running `mor-launch` no longer starts the desktop UI.

**Comment by abs2023** [comment]
> I am not inputting the models by hand onto the `models_config.json` file, but instead codegen it based on the data in the F# scripts I am using, so it was quite easy for me to adapt it to the new schema. Now that I've done this, I see that I am not getting warnings about it failing to load. Take a look at what sort of message I got yesterday in the terminal:
> 
> ```
> 2024-12-06T18:00:22.621162643   WARN    MODEL_LOADER    failed to unmarshal to new models config, trying legacy
> 2024-12-06T18:00:22.621251397   WARN    failed to load model config, running with empty: invalid models config: validator: (nil config.ModelConfigs)
> ```
> 
> This is a warning, but it should have been an error.

didn't want it to be a fail ... may change later, but needed to let the proxy-router continue to boot

**Comment by abs2023** [comment]
> ![image](https://private-user-images.githubusercontent.com/6266635/393501339-27726459-48e4-4a17-92ca-ebf267cb22b0.png? Ok, the first issue I am running into is with the proxy router on the consumer side. I got the 1.2 release for the mainnet, but it's telling me it's configured for the testnet here.

It's not configured for testnet, your Mac's keychain still has testnet cruft in it.  
once you get into the UI Desktop, you need to reset settings if you're going to switch to mainnet work.  Unfortunately, the mac keychain holds on to chainid and ethnodes (as well as wallet id) and needs to be reset.  
you can also use the `APP_RESET_KEYCHAIN=` in the .env file to force a reset: 

1. Make sure all morpheus related apps are closed
2. edit the .env and set APP_RESET_KEYCHAIN=true (also make sure the vars are set for the chain you want)
3. Start ./mor-launcher (you should see errors in the proxy-router startup and the UI should show terms and conditions) 
4. Ctrl-C in the Terminal where you started the launcher (closes all processes) 
5. re-edit the .env and set APP_RESET_KEYCHAIN=false
6. ./mor-launcher and should start new (where you should be able to recover wallet from mnemonic or privatekey)

**Comment by mrakgr** [comment]
I'll give that a try tomorrow. I guess there is no need to teach me how to build the desktop UI anymore.

**Comment by mrakgr** [comment]
Let me just say, that even though I didn't know about the `APP_RESET_KEYCHAIN`, it did occur to me that some stale data was in the cache, but trying to purge it by creating a new wallet didn't work.

**Comment by mrakgr** [comment]
```
Loaded config: {App:{ResetKeychain:false} Blockchain:{ChainID:42161 EthNodeAddress: EthLegacyTx:false ExplorerApiUrl:https://api.arbiscan.io/api ExplorerRetryDelay:0s ExplorerMaxRetries:0 UseSubscriptions:false PollingInterval:10s MaxReconnects:30 Multicall3Addr:<nil>} Environment:development Marketplace:{DiamondContractAddress:0xDE819AaEE474626E3f34Ef0263373357e5a6C71b MorTokenAddress:0x092bAaDB7DEf4C3981454dD9c0A0D7FF07bCFc86 WalletPrivateKey:<nil>} Log:{Color:true FolderPath: IsProd:false JSON:false LevelApp:debug LevelConnection:info LevelProxy:info LevelScheduler:info LevelContract: LevelRPC:info LevelBadger:} Proxy:{Address:0.0.0.0:3333 StoragePath:.\data\ StoreChatContext:true ForwardChatContext:true ModelsConfigPath: RatingConfigPath:./rating-config.json} System:{Enable:false LocalPortRange:1024 65535 NetdevMaxBacklog:100000 RlimitHard:524288 RlimitSoft:524288 Somaxconn: TcpMaxSynBacklog:100000} Web:{Address:0.0.0.0:8082 PublicUrl:http://localhost:8082}}
2024-12-10T09:33:29.5522793     INFO    APP     proxy-router v1.2.0
2024-12-10T09:33:29.5549034     INFO    RPC     using eth node address configured in keychain
cannot connect to ethereum node: configured chainID (42161) does not match eth node chain ID (421614)
2024/12/10 09:33:30 exit status 1
```

It says that `App:{ResetKeychain:false}` even though I've set it to true in the config file.

**Comment by mrakgr** [comment]
No, I cannot delete the keychain using `APP_RESET_KEYCHAIN=true`. Where is it storing the keychain? I am using a Windows PC at home. It'd be best if I could delete it by hand.

**Comment by mrakgr** [comment]
Given the situation, I'll go with the WSL plan. I'll compile the proxy router in WSL and debug it from there. Maybe I'll figure out where it is storing the keychain by looking at the source.

**Comment by mrakgr** [comment]
![image](https://github.com/user-attachments/assets/a116e8ef-aa86-46b1-b05d-3d6c13d750c4)
Maybe it's here in `C:\Users\mrakg\AppData\Roaming\morpheus-ui`?

**Comment by mrakgr** [comment]
Erasing that whole directory didn't remove the keychain. So the data has to be in the registry then.

**Comment by mrakgr** [comment]
No, I give up. It's not in the Windows registry either.

**Comment by abs2023** [comment]
@alex-sandrk or @shev-titan ... where is the "keychain" info stored in windows machine ... Marko is getting an issue when moving from testnet to mainnet and the morpheus-ui is not releasing or resetting that data

**Comment by abs2023** [comment]
> When I run `mor-launch` here is what it says at the top.
> 
> ```
> 2024/12/10 09:33:25 fork/exec ./morpheus-ui-${VFULL}-x64-win.exe: The system cannot find the file specified.
> INFO [                    main] build info | tid="10876" timestamp=1733819605 build=3256 commit="558f44bf"
> ```
> 
> Is it actually doing string interpolation with the `${VFULL}` variable here? It feels like it using it as a raw string.

Got this one, thanks..updating this and the ubuntu build job...the string interpolation was incorrect for non-mac jobs.  Should have an update out soon.

**Comment by abs2023** [comment]
@mrakgr Updated builds are here: https://github.com/Lumerin-protocol/Morpheus-Lumerin-Node/releases/tag/v1.4.0 
tested on both Win and Ubuntu and getting good startup at this point.

**Comment by mrakgr** [comment]
![image](https://github.com/user-attachments/assets/48ca12ce-8151-4f40-b1b0-1af2512f786a)
Unfortunately, you still haven't fixed the keyring issue. Setting `APP_RESET_KEYCHAIN=true` to reset the keyring still doesn't work for me.

**Comment by mrakgr** [comment]
![image](https://github.com/user-attachments/assets/2b044f49-3d9b-4e93-8d8b-40e472599c72)
I don't get this at all. I am printing out all the environment variables loaded by godotend, and it's telling me that `APP_RESET_KEYCHAIN=false` even though it's literally set to true in the `.env` file.
![image](https://github.com/user-attachments/assets/c813ef84-42b4-4252-b4b9-545869e8574c)

**Comment by mrakgr** [comment]
Maybe it's initially set to false, and the load isn't overwriting it?

**Comment by mrakgr** [comment]
![image](https://github.com/user-attachments/assets/3c844cdc-00de-4c9c-9158-068a1fbaed27)
This is almost certainly the error.

**Comment by mrakgr** [comment]
![image](https://github.com/user-attachments/assets/03ba376b-fe2d-484d-9936-dc2a94d3914b)
Oh, damn. Nevermind. I've been wasting my time debugging this only to realize the relevant line is present on the last line in the .env file!

**Comment by mrakgr** [comment]
Agh! That's what's been setting it to false!
